### ISSUE TITLE
add support for reply randomize

### ISSUE THREAD

**Issue by yeuem1vannam** [hellostealth/stealth#143]
Hello,

I think it is good if the `stealth` support the set of the reply text from the template so that with the same question, the user will be received a slightly different text.

I think it can be done by an array field template
```yaml
# bot/replies/flow_name/state_name.yml
- type: text
  text:
    - Hello there, how are you?
    - Yo, how is your day?
- type: text
  text: Looking for something new?
```
And replace 

https://github.com/hellostealth/stealth-facebook/blob/9d38f5001359e516d2d919296a6f7aff29f97da8/lib/stealth/services/facebook/reply_handler.rb#L24

with

```ruby
# lib/stealth/services/facebook/reply_handler.rb#L24
template['message']['text'] = reply['text'].is_an?(Array) ? reply['text'].sample : reply['text']
```

How you you think?
