### ISSUE TITLE
Configuration in initialiser ignored

### ISSUE THREAD

**Issue by malkovro** [hellostealth/stealth#278]
Hello there 👋🏼!

I have been playing a bit more with the framework and started to loose patience waiting for my own messages to arrive while debugging 😅.
I then tried to use the config associated mentioned in the [changelog](https://github.com/hellostealth/stealth/blob/master/CHANGELOG.md#enhancements) _Stealth.config.auto_insert_delays_  to remove them altogether but could not make it work… so I investigated why 🙃

- Whenever a new message arrives through a webhook, a job is pushed onto the queue.
- The job is accepted by one of the Sidekiq process and a [`Stealth::Dispatcher`](https://github.com/hellostealth/stealth/blob/master/lib/stealth/dispatcher.rb#L31-L40) takes care of  instantiating the appropriate MessageHandler adapter and pipe the request into the main controller

At this step the [Dispatcher ](https://github.com/hellostealth/stealth/blob/master/lib/stealth/dispatcher.rb#L34) is looking for a config value whether to log or not the message.

To do so, it sends a message on the module [Stealth](https://github.com/hellostealth/stealth/blob/master/lib/stealth/base.rb#L42) who in turns looks for `Thread.current[:configuration]`…
There seems to be nothing in there so it starts the `load_services_config` which loads the services.yaml file back again.

At this point any customisation of the configuration done in the `app/boot.rb` or any initialisers (as mentionned in the changelog) is lost because the `load_environment` message is not called. 

Additionally, some values, if specified to false, are ignored because of the `||=` syntax.

Example :

I wanted to disable the delay directly in my _service.yml_ with:
```yaml
default: &default
  auto_insert_delays: false # Does not work because the default value takes over the logical expression, see. https://github.com/hellostealth/stealth/blob/master/lib/stealth/base.rb#L76
  dynamic_delay_muliplier: 0.1 # Does work because it evaluates to true

  # /***/
```

I tried to take a look at how the specs are written to understand better how the delays are managed there but a `before(:each) ` block sets the right value for the `config.auto_insert_delays` which is not how this works once it is "required into sidekiq".

I am not particularly familiar with the `Thread.current` part so I might be missing a (big) point here🙏🏼. **If not then I would be glad to contribute in a way to fix/refactor the configuration section.**

---
Quick fix (that does not solve the initialisers ignored) in the case of the _auto_insert_delays_ would be to change line 76 of the [set_config_defaults](https://github.com/hellostealth/stealth/blob/master/lib/stealth/base.rb#L76) to something like:
```ruby
  config.auto_insert_delays ||= config.auto_insert_delays.nil?
```

👂🏽
