### ISSUE TITLE
Dynamic Delays

### ISSUE THREAD

**Issue by mgomes** [hellostealth/stealth#86]
Add an option for `delay` reply types called `dynamic`. It would look this within a reply:

```yml
- reply_type: text
  text: "Hello World!"
- reply_type: delay
  duration: dynamic
```

The calculated delay would be dynamic and based on the previous reply type and length. So for example, a short text like "Hello World!" would require a short delay of maybe 1 second. An image or a long paragraph would require a larger one.
